// 300-399/41-react-typescript/src/index.tsx
import React, { Component } from "react";
import { AgGridReact } from "ag-grid-react";
import { render } from "react-dom";

import { ColDef } from 'ag-grid-community'

import "ag-grid-community/dist/styles/ag-grid.css";
import "ag-grid-community/dist/styles/ag-theme-alpine.css";

interface Car {
  make: string, 
  model: string, 
  price: number
}

interface AppProps {}

interface AppState {
  columnDefs: ColDef[];
  rowData: Car[];
}

class App extends Component<AppProps, AppState> {

  constructor(props) {
    super(props);
    this.state = {
      columnDefs: [
        { headerName: "Make", field: "make" },
        { headerName: "Model", field: "model" },
        { headerName: "Price", field: "price" },
        { headerName: "Make", field: "make" },
        { headerName: "Model", field: "model" },
        { headerName: "Price", field: "price" }
      ],
      rowData: [
        { make: "Toyota", model: "Celica", price: 35000 },
        { make: "Ford", model: "Mondeo", price: 32000 },
        { make: "Porsche", model: "Boxter", price: 72000 },
        { make: "Toyota", model: "Celica", price: 35000 },
        { make: "Ford", model: "Mondeo", price: 32000 },
        { make: "Porsche", model: "Boxter", price: 72000 },
        { make: "Toyota", model: "Celica", price: 35000 },
        { make: "Ford", model: "Mondeo", price: 32000 },
        { make: "Porsche", model: "Boxter", price: 72000 },
        { make: "Toyota", model: "Celica", price: 35000 },
        { make: "Ford", model: "Mondeo", price: 32000 },
        { make: "Porsche", model: "Boxter", price: 72000 }
      ]
    };
  }

  onFirstDataRendered = params => {
    params.api.sizeColumnsToFit();
  };

  render() {
    return (
      <div
        className="ag-theme-alpine"
        style={{ width: "600px" }}
      >
        <AgGridReact
          columnDefs={this.state.columnDefs}
          rowData={this.state.rowData}
          onFirstDataRendered={this.onFirstDataRendered}
          domLayout="autoHeight"
        />
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));

// 300-399/35-web-components-1/src/index.js


class AgGrid extends HTMLElement {
  constructor() {
    super();

    this.innerHTML = `
      <div id="myGrid" style="height: 600px;width:500px;" class="ag-theme-alpine"></div> 
    `;

    this.columnDefs = [
      { headerName: "Make", field: "make", rowDrag: true },
      { headerName: "Model", field: "model" },
      { headerName: "Price", field: "price" }
    ];

    this.rowData = [
      { make: "Toyota", model: "Celica", price: 35000 },
      { make: "Ford", model: "Mondeo", price: 32000 },
      { make: "Porsche", model: "Boxter", price: 72000 },
      { make: "Toyota", model: "Celica", price: 35000 },
      { make: "Ford", model: "Mondeo", price: 32000 },
      { make: "Porsche", model: "Boxter", price: 72000 },
      { make: "Toyota", model: "Celica", price: 35000 },
      { make: "Ford", model: "Mondeo", price: 32000 },
      { make: "Porsche", model: "Boxter", price: 72000 },
      { make: "Toyota", model: "Celica", price: 35000 },
      { make: "Ford", model: "Mondeo", price: 32000 },
      { make: "Porsche", model: "Boxter", price: 72000 },
    ];

    this.gridOptions = {
      columnDefs: this.columnDefs,
      rowData: this.rowData,
      enableRangeSelection: true,
    };
  }

  connectedCallback() {
    var eGridDiv = document.querySelector("#myGrid");
    new agGrid.Grid(eGridDiv, this.gridOptions);
  }
}

window.customElements.define('my-grid', AgGrid);
