// 1-99/84-performance-test-react-redux-vs-vanilla-js/react_redux/src/App.js
import React, { Component, Fragment } from 'react';
import './App.css';

import { AgGridReact } from 'ag-grid-react';
import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-balham.css';
import 'ag-grid-enterprise';

import { connect } from 'react-redux';
import * as actions from './store/actions';

// HOW TO GET REFERENCES TO 100 DIFFERENT (UNIQUE) ROWS 
// const alreadyAdded = new Set();
// while (alreadyAdded.size < 100) {
//   const randRow = this.props.rowData[Math.floor(Math.random() * this.props.rowData.length)];
//   if (alreadyAdded.has(randRow)) continue;
//   alreadyAdded.add(randRow)
// }

class App extends Component {

  componentDidMount() {
    // not using redux thunk / asynchronous action setters
    fetch('https://raw.githubusercontent.com/ag-grid/ag-grid/master/packages/ag-grid-docs/src/olympicWinnersSmall.json')
      .then(res => res.json())
      .then(data => {
        data.forEach(d => d.id = this.createUniqueRandomSymbol(data));
        this.props.onInitRowData(data);
      })
      .catch(error => {
        console.log(error);
      })
  }

  onGridReady(params) {
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;
  }

  update1RowHandler = () => {
    const randInd = this.getRandInd();
    this.props.onUpdateRows([randInd]);
  }

  delete1RowHandler = () => {
    const randInd = this.getRandInd();
    this.props.onDeleteRows([randInd]);
  }

  add1RowHandler = () => {
    const randInd = this.getRandInd();
    const symbol = this.createUniqueRandomSymbol();
    this.props.onAddRows([randInd], [symbol]);
  }

  update100RowsHandler = () => {
    const indexSet = new Set();
    while (indexSet.size < 100) {
      const randInd = this.getRandInd();
      if (indexSet.has(randInd)) {
        continue;
      }
      indexSet.add(randInd);
    }
    this.props.onUpdateRows([...indexSet]);
  }

  delete100RowsHandler = () => {
    const indexSet = new Set();
    while (indexSet.size < 100) {
      const randInd = this.getRandInd();
      if (indexSet.has(randInd)) {
        continue;
      }
      indexSet.add(randInd);
    }
    this.props.onDeleteRows([...indexSet]);
  }

  add100RowsHandler = () => {
    const indexSet = new Set();
    const symbolSet = new Set();
    while (indexSet.size < 100) {
      const randInd = this.getRandInd();
      const symbol = this.createUniqueRandomSymbol();
      if (indexSet.has(randInd) || symbolSet.has(symbol)) {
        continue;
      }
      indexSet.add(randInd);
      symbolSet.add(symbol);
    }
    this.props.onAddRows([...indexSet], [...symbolSet]);
  }

  getRandInd() {
    return Math.floor(Math.random() * this.props.rowData.length);
  }

  createUniqueRandomSymbol(data = this.props.rowData) {
    var symbol;
    var possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

    var isUnique = false;
    while (!isUnique) {
      symbol = '';
      for (var i = 0; i < 10; i++) {
        symbol += possible.charAt(Math.floor(Math.random() * possible.length));
      }
      isUnique = true;
      if (data.some(row => row.id === symbol)) {
        isUnique = false;
      }
    }
    return symbol;
  }


  render() {
    return (
      <Fragment>
        <div className="button-wrap">
          <button onClick={this.update1RowHandler}>Update 1 Row</button>
          <button onClick={this.delete1RowHandler}>Delete 1 Row</button>
          <button onClick={this.add1RowHandler}>Add 1 Row</button>
          <br />
          <button onClick={this.update100RowsHandler}>Update 100 Rows</button>
          <button onClick={this.delete100RowsHandler}>Delete 100 Rows</button>
          <button onClick={this.add100RowsHandler}>Add 100 Rows</button>
        </div>
        <div
          className="ag-theme-balham"
          style={{
            height: '90vh',
            // width: '100%'
          }}>
          <AgGridReact
            columnDefs={[
              { headerName: 'Athlete', field: 'athlete' },
              { headerName: 'Sport', field: 'sport' },
              { headerName: 'Age', field: 'age' },
              { headerName: 'Year', field: 'year' },
              { headerName: 'Date', field: 'date' },
              { headerName: 'Gold', field: 'gold' },
              { headerName: 'Silver', field: 'silver' },
              { headerName: 'Bronze', field: 'bronze' }
            ]}
            rowData={this.props.rowData}
            defaultColDef={{ width: 150 }}
            onGridReady={this.onGridReady}
            deltaRowDataMode={true}
            getRowNodeId={data => data.id}>
          </AgGridReact>
        </div>

      </Fragment>
    );
  }
}

const mapStateToProps = state => {
  return {
    rowData: state.rowData
  }
}

const mapDispatchToProps = dispatch => {
  return {
    onInitRowData: rowData => dispatch(actions.initRowData(rowData)),
    onUpdateRows: indexArr => dispatch(actions.updateRows(indexArr)),
    onDeleteRows: indexArr => dispatch(actions.deleteRows(indexArr)),
    onAddRows: (indexArr, symbolArr) => dispatch(actions.addRows(indexArr, symbolArr)),
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(App);

// 300-399/05-ngrx-ssrm-editing/src/app/app.component.ts
import { Component, ViewChild } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { AllModules } from "@ag-grid-enterprise/all-modules";
import "@ag-grid-community/all-modules/dist/styles/ag-grid.css";
import "@ag-grid-community/all-modules/dist/styles/ag-theme-balham.css";

@Component({
  selector: "app-root",
  template: `
  <app-my-counter></app-my-counter>
    <div style="height: 80vh; padding-top: 26px; box-sizing: border-box;">
      <ag-grid-angular
        #agGrid
        style="width: 100%; height: 100%;"
        id="myGrid"
        class="ag-theme-balham"
        [modules]="modules"
        [columnDefs]="columnDefs"
        [defaultColDef]="defaultColDef"
        [rowModelType]="rowModelType"
        [cacheBlockSize]="cacheBlockSize"
        [maxBlocksInCache]="maxBlocksInCache"
        [animateRows]="true"
        [debug]="true"
        [rowData]="rowData"
        (gridReady)="onGridReady($event)"
      ></ag-grid-angular>
    </div>
  `
})
export class AppComponent {
  private gridApi;
  private gridColumnApi;
  public modules: Module[] = AllModules;

  private columnDefs;
  private defaultColDef;
  private rowModelType;
  private cacheBlockSize;
  private maxBlocksInCache;
  private rowData: [];

  constructor(private http: HttpClient) {
    this.columnDefs = [
      { field: "id" },
      {
        field: "athlete",
        width: 150
      },
      { field: "age" },
      { field: "country" },
      { field: "year" },
      { field: "sport" },
      { field: "gold" },
      { field: "silver" },
      { field: "bronze" }
    ];
    this.defaultColDef = {
      width: 120,
      resizable: true
    };
    this.rowModelType = "serverSide";
    this.cacheBlockSize = 100;
    this.maxBlocksInCache = 10;
  }

  onGridReady(params) {
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;

    this.http
      .get("https://raw.githubusercontent.com/ag-grid/ag-grid/master/packages/ag-grid-docs/src/olympicWinners.json")
      .subscribe((data) => {
        var idSequence = 0;
        data.forEach(function(item) {
          item.id = idSequence++;
        });
        var server = new FakeServer(data);
        var datasource = new ServerSideDatasource(server);
        params.api.setServerSideDatasource(datasource);
      });
  }
}

function ServerSideDatasource(server) {
  return {
    getRows: function(params) {
      setTimeout(function() {
        var response = server.getResponse(params.request);
        if (response.success) {
          params.successCallback(response.rows, response.lastRow);
        } else {
          params.failCallback();
        }
      }, 500);
    }
  };
}

function FakeServer(allData) {
  return {
    getResponse: function(request) {
      console.log("asking for rows: " + request.startRow + " to " + request.endRow);
      var rowsThisPage = allData.slice(request.startRow, request.endRow);
      var lastRow = allData.length <= request.endRow ? data.length : -1;
      return {
        success: true,
        rows: rowsThisPage,
        lastRow: lastRow
      };
    }
  };
}
