// 300-399/64-copying-and-pasting-into-a-non-editable-input-renderer/app/child-message-renderer.component.ts
import { Component } from '@angular/core';
import { ICellRendererAngularComp } from '@ag-grid-community/angular';

@Component({
  selector: 'child-cell',
  template: `
  <span
    ><input></span
  >`,
  styles: [
    `
      .btn {
        line-height: 0.5;
      }
    `,
  ],
})
export class ChildMessageRenderer implements ICellRendererAngularComp {
  public params: any;

  agInit(params: any): void {
    this.params = params;
  }

  public invokeParentMethod() {
    this.params.context.componentParent.methodFromParent(
      `Row: ${this.params.node.rowIndex}, Col: ${this.params.colDef.headerName}`
    );
  }

  refresh(): boolean {
    return false;
  }
}

// 1-99/61-keeping-row-selection-after-clicking-button/childMessageRenderer.jsx
import React, {Component} from "react";

export default class ChildMessageRenderer extends Component {
    constructor(props) {
        super(props);

        this.invokeParentMethod = this.invokeParentMethod.bind(this);
    }

    invokeParentMethod() {
      // pass this.props.node into the callback so child the row can be unselected
        this.props.context.componentParent.methodFromParent(`Row: ${this.props.node.rowIndex}, Col: ${this.props.colDef.headerName}`, this.props.node);
    }

    render() {
        return (
            <span><button style={{height: 20, lineHeight: 0.5}} onClick={this.invokeParentMethod} className="btn btn-info">Invoke Parent</button></span>
        );
    }
};
